In [1]:
%matplotlib widget

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [114]:
dt = .001
tf = 100
t = np.arange(0, tf, dt)

m1 = 1000
m2 = 1
G = 0.001

r10 = np.array([0, 0])
r20 = np.array([1, 0])

v10 = np.array([0,-0.001])
v20 = np.array([0,1])

r1 = [r10]
r2 = [r20]

v1 = [v10]
v2 = [v20]

def f(r):
    return -G*m1*m2*r/np.sum((r10-r20)**2)**(3/2)

def acc(f, m):
    return f/m

def vel(v, a):
    return v + a*dt

def pos(r, v):
    return r + v*dt

r1t = r1[-1]
r2t = r2[-1]
v1t = v1[-1]
v2t = v2[-1]

In [115]:
for i in t:
    f1t = f(r1t-r2t)
    f2t = -f1t
    a1t = acc(f1t, m1)
    a2t = acc(f2t, m2)
    v1t = vel(v1t, a1t)
    v2t = vel(v2t, a2t)
    r1t = pos(r1t, v1t)
    r2t = pos(r2t, v2t)
    r1.append(r1t)
    r2.append(r2t)
    v1.append(v1t)
    v2.append(v2t)

In [116]:
fig, ax = plt.subplots()#subplot_kw=dict(aspect='equal'))
ax.plot(*zip(*r1), '-', label="sun",)
ax.plot(*zip(*r2), '-', label="earth")
ax.set_aspect(1)
#ax.set_xlim(-5,5)
#ax.set_ylim(-5,5)
ax.legend()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [241]:
plt.close('all')

In [100]:
r2

[array([1, 0]),
 array([0.999999, 0.002   ]),
 array([0.999997, 0.004   ]),
 array([0.999994  , 0.00599999]),
 array([0.99999   , 0.00799998]),
 array([0.999985  , 0.00999996]),
 array([0.999979  , 0.01199993]),
 array([0.999972  , 0.01399989]),
 array([0.999964  , 0.01599983]),
 array([0.999955  , 0.01799976]),
 array([0.999945  , 0.01999967]),
 array([0.999934  , 0.02199956]),
 array([0.999922  , 0.02399943]),
 array([0.999909  , 0.02599927]),
 array([0.999895  , 0.02799909]),
 array([0.99988   , 0.02999888]),
 array([0.999864  , 0.03199864]),
 array([0.999847  , 0.03399837]),
 array([0.999829  , 0.03599806]),
 array([0.99981001, 0.03799772]),
 array([0.99979001, 0.03999734]),
 array([0.99976901, 0.04199692]),
 array([0.99974701, 0.04399646]),
 array([0.99972401, 0.04599595]),
 array([0.99970001, 0.0479954 ]),
 array([0.99967502, 0.0499948 ]),
 array([0.99964902, 0.05199415]),
 array([0.99962202, 0.05399345]),
 array([0.99959403, 0.05599269]),
 array([0.99956503, 0.05799188]),
 array

In [101]:
r2t

array([0.06509446, 0.00361996])

In [102]:
r1t-r2t

array([-650.00968709,  163.79675179])