In [124]:
%matplotlib widget

In [125]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [245]:
dt = .001
tf = 10
t = np.arange(0, tf, dt)

m1 = 1
m2 = 1000
G = .001

r10 = np.array([1, 0])
r20 = np.array([0, 0])

v10 = np.array([0,.7])
v20 = np.array([0,0])

r1 = [r10]
r2 = [r20]

v1 = [v10]
v2 = [v20]

def f(r):
    return -G*m1*m2/np.sum(np.abs(r**3))*r

def acc(f, m):
    return f/m

def vel(v, a):
    return v + a*dt

def pos(r, v):
    return r + v*dt

r1t = r1[-1]
r2t = r2[-1]
v1t = v1[-1]
v2t = v2[-1]

In [246]:
for i in t:
    f1t = f(r1t-r2t)
    f2t = -f1t
    a1t = acc(f1t, m1)
    a2t = acc(f2t, m2)
    v1t = vel(v1t, a1t)
    v2t = vel(v2t, a2t)
    r1t = pos(r1t, v1t)
    r2t = pos(r2t, v2t)
    r1.append(r1t)
    r2.append(r2t)
    v1.append(v1t)
    v2.append(v2t)

In [247]:
fig, ax = plt.subplots()
ax.scatter(*zip(*r1), marker='.', label="m1",)
ax.scatter(*zip(*r2), label="m2")
#ax.set_xlim(-5,5)
#ax.set_ylim(-5,5)
ax.legend()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [241]:
plt.close('all')

In [98]:
r1t

array([-649.94459263,  163.80037175])

In [101]:
r2t

array([0.06509446, 0.00361996])

In [102]:
r1t-r2t

array([-650.00968709,  163.79675179])